#!/usr/bin/env python
# -*- coding: utf-8 -*-

######################################################################
# Copyright 2017 Telera www.telera.eu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
######################################################################


import sys
import shlex

import guest_exec as ge

def main():
    import os
    if len(sys.argv) == 3:
        cmd = shlex.split(sys.argv[2].decode('base64'))
        out = ge.guest_exec(sys.argv[1], cmd[0], cmd[1:], wait=True)
        print out[1],
        print >> sys.stderr, out[2],
        sys.exit(out[0])
    else:
        print >>sys.stderr, "Usage %s <domain> <cmd> [<args>, ...]" % sys.argv[0]
        sys.exit(os.EX_USAGE)

if __name__ == '__main__':
    main()
