#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import shlex

import guest_exec as ge

def main():
    import os
    if len(sys.argv) == 3:
        cmd = shlex.split(sys.argv[2].decode('base64'))
        out = ge.guest_exec(sys.argv[1], cmd[0], cmd[1:], wait=True)
        print out[1],
        print >> sys.stderr, out[2],
        sys.exit(out[0])
    else:
        print >>sys.stderr, "Usage %s <domain> <cmd> [<args>, ...]" % sys.argv[0]
        sys.exit(os.EX_USAGE)

if __name__ == '__main__':
    main()
