#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys

import guest_exec

def main():
    import os
    if len(sys.argv) > 2:
        out = guest_exec.guest_exec(sys.argv[1], sys.argv[2], sys.argv[3:], wait=True)
        print out[1],
        print >> sys.stderr, out[2],
        sys.exit(out[0])
    else:
        print >>sys.stderr, "Usage %s <domain> <cmd> [<args>, ...]" % sys.argv[0]
        sys.exit(os.EX_USAGE)

if __name__ == '__main__':
    main()
