#!/usr/bin/env python3
# -*- coding: utf-8 -*-

######################################################################
# Copyright 2017 Telera www.telera.eu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
######################################################################


import sys

import guest_exec as ge

GUEST_PATH = '/etc/one-user-action'

def main():
    import os
    if len(sys.argv) == 5:
        out = ge.guest_exec(sys.argv[1],
                GUEST_PATH + '/network_ip_alias',
                sys.argv[2:5], wait=True)
        sys.stdout.buffer.write(out[1])
        sys.stderr.buffer.write(out[2])
        sys.exit(out[0])
    else:
        print("Usage %s <domain> {add|delete} <intf_idex> <addr/mask>" % sys.argv[0],
                file=sys.stderr)
        sys.exit(os.EX_USAGE)

if __name__ == '__main__':
    main()
