#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys

import guest_exec as ge

GUEST_PATH = '/etc/one-user-action'

def main():
    import os
    if len(sys.argv) == 3:
        out = ge.guest_exec(sys.argv[1],
                GUEST_PATH + '/set_password',
                [sys.argv[2]], wait=True)
        print out[1],
        print >> sys.stderr, out[2],
        sys.exit(out[0])
    else:
        print >> sys.stderr, "Usage %s <domain> <new_root_password>" % sys.argv[0]
        sys.exit(os.EX_USAGE)

if __name__ == '__main__':
    main()
