#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys

import guest_exec as ge

GUEST_PATH = '/etc/one-user-action'

def main():
    print repr(sys.argv)
    if len(sys.argv) > 2:
        out = ge.guest_exec(sys.argv[1],
                'sh',
                ['-c', "echo -n 'Hostname:'; hostname; echo -n 'PWD: '; pwd; "
			"id; echo 'Environment:'; set; echo 'User string:[%s]'" 
				% sys.argv[2]], wait=True)
        print out[1],
        print >> sys.stderr, out[2],
        sys.exit(out[0])
    else:
        print "Usage %s <domain> <test string>" % sys.argv[0]

if __name__ == '__main__':
    main()
