#!/bin/bash

iptables-save >/var/tmp/iptables-save.`date +%Y%m%d%H%M%S`
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
iptables -t nat -F
iptables -t mangle -F
iptables -F
iptables -X
