#!/bin/bash

function export_rc_vars
{
    if [ -f $1 ] ; then
        ONE_VARS=`cat $1 | egrep -e '^[a-zA-Z\-\_0-9]*=' | sed 's/=.*$//'`

        . $1

        for v in $ONE_VARS; do
            export $v
        done
    fi
}

function execute_scripts {
    SCRIPTS_DIR="/etc/one-context.d"
    for script in $SCRIPTS_DIR/??-network; do
        $script
    done
}

function start {
    CONTEXT_DEV=`blkid -l -t LABEL="CONTEXT" -o device`
    if [ -e "$CONTEXT_DEV" ]; then
        mount -t iso9660 -L CONTEXT -o ro /mnt
        if [ -f /mnt/context.sh ]; then
            export_rc_vars /mnt/context.sh
        fi

        execute_scripts

        umount /mnt
    else
        if type vmtoolsd ; then
            vmtoolsd --cmd 'info-get guestinfo.opennebula.context' | openssl base64 -d > /tmp/context.sh
            export_rc_vars /tmp/context.sh
        fi

        execute_scripts
    fi
}

start
